---
- name: Configure RDP on Windows 10
  hosts: windows
  tasks:
    - name: Enable RDP
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present

    - name: Allow RDP through the Windows Firewall
      win_firewall_rule:
        name: "Remote Desktop"
        enable: yes
        direction: in
        action: allow
        localport: all
        remoteport: all
        protocol: tcp
        profile: any
